"""Read-only Intervention API routes (mid-priority #6).

Exposes the intervention candidates generated by the opportunity pipeline so
the frontend can display graded (A/B/C) directions and their hard-gate results.
GET-only — no write operations.
"""

import json
import logging

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from app.api.deps import get_db_session
from app.db.models import InterventionCandidate
from app.db.repositories import intervention_repo
from app.schemas.schemas import InterventionOut

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api", tags=["interventions"])


def _to_out(item: InterventionCandidate) -> InterventionOut:
    return InterventionOut(
        id=item.id,
        task_id=item.task_id,
        gap_id=item.gap_id,
        contract_id=item.contract_id,
        intervention_type=item.intervention_type,
        failure_mechanism=item.failure_mechanism,
        proposed_intervention=item.proposed_intervention,
        intermediate_effect=item.intermediate_effect,
        measurable_outcome=item.measurable_outcome,
        required_components=json.loads(item.required_components_json or "[]"),
        dependency_paper_ids=json.loads(item.dependency_paper_ids_json or "[]"),
        implementation_cost=item.implementation_cost,
        mechanism_confidence=item.mechanism_confidence,
        evidence_gate=item.evidence_gate or "UNKNOWN",
        novelty_gate=item.novelty_gate or "UNKNOWN",
        feasibility_gate=item.feasibility_gate or "UNKNOWN",
        gate_rationale=json.loads(item.gate_rationale_json or "{}"),
        confidence_tier=item.confidence_tier or "C",
        status=item.status or "candidate",
        created_at=item.created_at.isoformat() + "+00:00" if item.created_at else "",
    )


@router.get("/tasks/{task_id}/interventions", response_model=list[InterventionOut])
def list_interventions(
    task_id: str,
    contract_id: str | None = Query(None, description="Filter by contract ID"),
    db: Session = Depends(get_db_session),
):
    """List intervention candidates for a task (optionally scoped to a contract)."""
    items = intervention_repo.list_interventions_for_task(db, task_id, contract_id=contract_id)
    return [_to_out(i) for i in items]


@router.get("/interventions/{intervention_id}", response_model=InterventionOut)
def get_intervention(intervention_id: str, db: Session = Depends(get_db_session)):
    """Get a single intervention candidate by ID."""
    item = db.get(InterventionCandidate, intervention_id)
    if not item:
        raise HTTPException(status_code=404, detail="Intervention not found")
    return _to_out(item)
